---
title: "test"
author: "Xavier Bryant"
date: "25/03/2021"
output: html_document
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=8, fig.height=4)
library(tsoutliers)
library(knitr)
library(fpp2)
library(SWMPr)
library(forecast)
library(dygraphs)
library(dplyr)
library(TSstudio)
library(webshot)
```

```{r}
library(fpp2)
library(tsoutliers)
library()
marathon <- marathon 
par(mfrow=c(1,3))
marathonts1<-ts(marathon[1:25],start=c(1897),end=c(1923),freq=1)
marathonts2<-ts(marathon[25:56],start=c(1924),end=c(1953),freq=1)
marathonts3<-ts(marathon[56:120],start=c(1954),freq=1)
plot(marathonts1,main="Years 1897-1923")
plot(marathonts2,main="Years 1924-1953")
plot(marathonts3,main="Years 1954-2016")
```



```{r}
par(mfrow=c(1,3))
lmarathonts1 <- log(marathonts1)
dlmarathonts1 <- diff(lmarathonts1)
lmarathonts2 <- log(marathonts2)
dlmarathonts2 <- diff(lmarathonts2)
lmarathonts3 <- log(marathonts3)
dlmarathonts3 <- diff(lmarathonts3)
plot(dlmarathonts1)+title(" Log-return: Years 1897-1923 ")
acf(dlmarathonts1, lag=150)
pacf(dlmarathonts1, lag=150)
```


```{r}
auto.arima(lmarathonts1, ic="aic")
tso(lmarathonts1, types = c("A0", "LS", "TC"))
```



```{r}
a=tso(lmarathonts1, types = c("A0", "LS", "TC"))
b=tso(lmarathonts2, types = c("A0", "LS", "TC"))
c=tso(lmarathonts3, types = c("A0", "LS", "TC"))

```




```{r}
par(mfrow=c(1,3))
plot(a)

plot(b)

plot(c)
```

```{r}
outmarathonts1=tso(lmarathonts1, types = c("A0", "LS", "TC"))
outmarathonts2=tso(lmarathonts2, types = c("A0", "LS", "TC"))
outmarathonts3=tso(lmarathonts3, types = c("A0", "LS", "TC"))
```

```{r}
par(mfrow=c(1,3))
plot(outmarathonts1)
plot(outmarathonts2)
plot(outmarathonts3)
```




```{r, echo=FALSE, fig.width=8, fig.height=4}

par(mfrow=c(1,3))

x=outmarathonts1$yadj
fit<-arima(x,order=c(0,1,1),include.mean=FALSE)
forecast<-predict(fit,n.ahead=50)
pm <- forecast(fit, h=12)
plot(pm)
x=outmarathonts2$yadj
fit<-arima(x,order=c(0,1,1),include.mean=FALSE)
forecast<-predict(fit,n.ahead=50)
pm <- forecast(fit, h=12)
plot(pm)
x=outmarathonts3$yadj
fit<-arima(x,order=c(0,1,1),include.mean=FALSE)
forecast<-predict(fit,n.ahead=50)
pm <- forecast(fit, h=12)
plot(pm)
```

